ASoC: samsung: i2s: Fix the checked out code style problems
This patch just fix the code style issues about required space
missing and redundant line continuations have been checked out:

./scripts/checkpatch.pl -f ./sound/soc/samsung/i2s.c
ERROR: space required before the open brace '{'
\#1033: FILE: sound/soc/samsung/i2s.c:1033:
+		if (!IS_ERR(i2s->op_clk)){

WARNING: Avoid unnecessary line continuations
\#1225: FILE: sound/soc/samsung/i2s.c:1225:
+		dev_err(&pdev->dev, "idma address is not"\

total: 1 errors, 1 warnings, 1398 lines checked

./sound/soc/samsung/i2s.c has style problems, please review.

If any of these errors are false positives, please report
them to the maintainer, see CHECKPATCH in MAINTAINERS.

Change-Id: I51f2bf0f6b203613b3a81d604b69c6e08ed97507
Signed-off-by: Huang Chao <chao7.huang@samsung.com>